### ISSUE TITLE
TreeRep.py also generates NJ output

### ISSUE THREAD

**Issue by mjhajharia** [rsonthal/TreeRep#3]
I tried executing TreeRep.py and got an adjacency matrix with twice the number of nodes, which is an attribute of neighbour join I think.  
<img width="391" alt="image" src="https://user-images.githubusercontent.com/55153708/105408970-b98e0500-5c55-11eb-8098-a4c9868545c1.png">

**Comment by rsonthal** [comment]
Yes, the matrix W will have double the size. But if you look at the matrix W, you might see that the a lot of the rows and columns are 0. 

Basically, for speed, we pre-allocate the matrix W, which could be unto twice as big. However, we do not necessarily use all of those entries.

**Comment by mjhajharia** [comment]
but that will create a problem I wanna reconstruct my original tree (wrt node labels, if node labels are meaningful).
I checked the paper which said it was the same size, so can I edit the code somewhere to get a matrix which is same sized.  Or is there some other function for reconstruction of the tree.

**Comment by rsonthal** [comment]
In the pytorch wrapper file add the line

`n = Main.eval('nv(G)')`

And then modify the line

`W = np.zeros_like(Main.dist)`

To 

`W = np.zeros((n,n))`

**Comment by mjhajharia** [comment]
did that. 
<img width="471" alt="image" src="https://user-images.githubusercontent.com/55153708/105411534-864d7500-5c59-11eb-9749-a81a08c93086.png">
its still showing an extra node.

**Comment by mjhajharia** [comment]
also, I was trying to figure this, but are the new nodes and old ones matched, as in, can I label the new adjacency matrix with old node labels?

**Comment by rsonthal** [comment]
The labels are matched! So if the old node was idx i, then the new node is still index i. 

There will always be new nodes. The old ones are like the leave nodes and sometimes you need to add more nodes to build the tree.

**Comment by mjhajharia** [comment]
Alright! so I can simply remove the last row and column and match the nodes to get final labelled results right?

**Comment by rsonthal** [comment]
Yes
